// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// read_parquet
List read_parquet(std::string filename, IntegerVector selected_col, LogicalVector filter, int read_row_size, int threads, int verbose);
RcppExport SEXP _RParquet_read_parquet(SEXP filenameSEXP, SEXP selected_colSEXP, SEXP filterSEXP, SEXP read_row_sizeSEXP, SEXP threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type selected_col(selected_colSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type filter(filterSEXP);
    Rcpp::traits::input_parameter< int >::type read_row_size(read_row_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(read_parquet(filename, selected_col, filter, read_row_size, threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// read_metadata
DataFrame read_metadata(std::string filename, bool details);
RcppExport SEXP _RParquet_read_metadata(SEXP filenameSEXP, SEXP detailsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< bool >::type details(detailsSEXP);
    rcpp_result_gen = Rcpp::wrap(read_metadata(filename, details));
    return rcpp_result_gen;
END_RCPP
}
// write_rparquet
int write_rparquet(DataFrame& df, std::string filename, CharacterVector col_types, IntegerVector selected_col, int group_rows, int verbose);
RcppExport SEXP _RParquet_write_rparquet(SEXP dfSEXP, SEXP filenameSEXP, SEXP col_typesSEXP, SEXP selected_colSEXP, SEXP group_rowsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type col_types(col_typesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type selected_col(selected_colSEXP);
    Rcpp::traits::input_parameter< int >::type group_rows(group_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(write_rparquet(df, filename, col_types, selected_col, group_rows, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RParquet_read_parquet", (DL_FUNC) &_RParquet_read_parquet, 6},
    {"_RParquet_read_metadata", (DL_FUNC) &_RParquet_read_metadata, 2},
    {"_RParquet_write_rparquet", (DL_FUNC) &_RParquet_write_rparquet, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_RParquet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
