# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_parquet <- function(filename, selected_col, filter, read_row_size, threads, verbose) {
    .Call('_RParquet_read_parquet', PACKAGE = 'RParquet', filename, selected_col, filter, read_row_size, threads, verbose)
}

read_metadata <- function(filename, details = FALSE) {
    .Call('_RParquet_read_metadata', PACKAGE = 'RParquet', filename, details)
}

write_rparquet <- function(df, filename, col_types, selected_col, group_rows, verbose) {
    .Call('_RParquet_write_rparquet', PACKAGE = 'RParquet', df, filename, col_types, selected_col, group_rows, verbose)
}

